In [12]:
#Task-1-Q:1: Write a function to compute 5/0 and use try/except to catch the exceptions. 

def compute():
    return 5/0
try:
    return 5/0
except ZeroDivisionError as ze:
    print("Incorrect division operation to divide by 0")


Incorrect division operation to divide by 0


In [19]:
#Q2:  Implement a Python program to generate all sentences where subject is in ["Americans",  "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].  
 
subjects=["Americans","Indians"]  
verbs=["play","watch"]  
objects=["Baseball","Cricket"] 

for i in subjects:
    for j in verbs:
        for k in objects:
            print(i+" "+j+" "+k)

print("\n\nsecond method:\n\n")
newlist = [(i+" "+j+" "+k) for i in subjects for j in verbs for k in objects]
for sent in newlist:
 print (sent)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


second method:


Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [37]:
#Task 2 Q1: Write a function so that the columns of the output matrix are powers of the input vector.   
#The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.


import numpy as np

def vendormat(inputarray,n,increasing):
    if not increasing:
        outmatx=np.array([x**(n-1-i) for x in inputarray for i in range(n)]).reshape(inputarray.size,n)
    
    else:
        outmatx=np.array([x**(i) for x in inputarray for i in range(n)]).reshape(inputarray.size,n)
    
    return outmatx

arr=np.array([1,2,3,4])
n=3
outmat=vendormat(arr,n,True)
outmat1=vendormat(arr,n,False)

print("Matrix in Increasing order:\n ",outmat)
print("\nMatrix in Decreasing order:\n ",outmat1)





Matrix in Increasing order:
  [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]

Matrix in Decreasing order:
  [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]
